apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hiwm
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0073-tenant/tkrw-pr712-0075-0073-app/devfile-sample-hiwm@sha256:d8ceb64a73799294898c34867358b3b371f95bb746366b46c3d15bfdf6f1b14a
        name: my-nodejs
        resources: {}
status: {}
